import os
from sys import argv
from server.devserver import server
from shutil import rmtree
from config import *

help_menu = f'''\
Welcome to {f['name']}

startproject - To start a new project with a default boiler template.

'''


def __templates(project_name, template):
    if template == 'settings':
        settings_template = f'''\
\'''
{f['name']} settings for {project_name} project.

Generated by '{f['name']} startproject' using {f['name']} {f['version']}.
\'''

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

'''
        return settings_template

    elif template == 'urls':
        urls_template = f'''\
\'''\
{f['name']} urls for {project_name} project.

Generated by '{f['name']} startproject' using {f['name']} {f['version']}.

\'''

from pysitemaker.url import urls


'''
        return urls_template

    else:
        return 'Nothing found !'


def pysitemaker(site_name):

    pass


def startproject(name, location='.'):
    os.chdir(os.path.join('.', location))
    os.mkdir(name)
    os.chdir(name)

    with open('settings.py', 'w') as settings:
        settings.write(__templates(project_name=name, template='settings'))

    with open('urls.py', 'w') as urls:
        urls.write(__templates(project_name=name, template='urls'))


def exec_from_command_line(argv):

    try:
        if argv[1] == '':
            print(help_menu)
        elif argv[1] == 'startproject':
            # args = ','.join(argv[2:])
            try:
                startproject(name=argv[2], location=argv[3])
            except:
                startproject(name=argv[2])
        elif argv[1] == 'startserver':
            server()
        elif argv[1] == 'rmproject':
            dir_exists = os.path.exists(argv[2])
            if dir_exists:
                rmtree(argv[2])
            else:
                print('Project not exists !')
    except Exception as e:
        print(e)
        FileExistsError('Project already exist !')
        # print(help_menu)
        print(argv[2:])
